### ISSUE TITLE
Data Input to ChildEntities2 vanishes 

### ISSUE THREAD

**Issue by kiran-b-a** [SAP-samples/fiori-elements-feature-showcase#31]
<img width="1840" alt="image" src="https://github.com/SAP-samples/fiori-elements-feature-showcase/assets/162103277/23ae7268-ded2-4fc4-8310-b8fb27b49ce1">

### How to Reproduce:

```bash
cds watch # in root
```
navigate to launchpad -> feature elements showcase -> click on create 
try to input anything within childentities2 section 
as soon as you enter the data vanishes in the create mode after you move out of the context

**Comment by schiwekM** [comment]
Hi @kiran-b-a,

this is because childEntity2 is an association to one in the data model and should be set via its foreign key. e.g. the fields actually are not intended for input.

On the latest main, I renamed the relation to 'association2one'. Moreover the section is no longer shown in edit mode and the fields are also marked as readonly so if they would be shown, they would not be editable.

Hope that clears things up.

BR,
Marten
